### ISSUE TITLE
import promisify causing compile issues

### ISSUE THREAD

**Issue by wmontgomery** [beekeeper-studio/cassandra-knex#1]
When attempting to include this package into the beekeeper-studios app, an unused import in the index.js (cassandra-knex/src/index.js) file is causing the application to crash and not compile. This could be because the application is using node 14.16.1?

Error message: 
![image](https://user-images.githubusercontent.com/314613/215655404-6295db38-354b-466d-ac87-278b5207c3ae.png)

Commenting it out helped, but not sure the purpose outside of maybe just left in there by accident?

**Comment by not-night-but** [comment]
@wmontgomery Hey sorry, I just saw this. Yeah promisify was used in other dialects, and I must've forgotten to remove it when copying over the imports.

I'm using node 16.14.2 locally so that discrepancy could definitely be the issue. I'll just remove the package entirely.

I'll also make sure to test with node 14 just in case

**Comment by not-night-but** [comment]
@wmontgomery all tests passing on node 14, removed the redundant import.
